### ISSUE TITLE
Is adapter needed for .net core project?

### ISSUE THREAD

**Issue by molequetu** [mattmorg55/KeycloakOwinAuthentication#20]
Hello, 

I would like to ask if you use the adapter in asp.net core projects. We are in the phase of migrating our asp.net MVC project
to .net core, and I was wandering if the adapter is supported in .net core project's or is not needed at all.

Thank you

**Comment by highbyte** [comment]
Hi,
I may be mistaken, but I don't think this library would work for .NET Core.

In ASP.NET Core Microsoft has implemented OpenId Connect "Authorization Code Flow" protocol (that Keycloak server implements) with in their own library, so a Keycloak-specific library should probably not be needed for MVC applications.
`Microsoft.AspNetCore.Authentication.OpenIdConnect`

For ASP.NET Core WebApi applications a simple JWT token validation library could probably be used instead.
`Microsoft.AspNetCore.Authentication.JwtBearer`

**Comment by molequetu** [comment]
Ok @highbyte  I was thinking the same thing. Thank you, cheers.

**Comment by molequetu** [comment]
Closed
